Description: This is the template for the containerised-giftcard-reader-lambda lambda function

Resources:
  ReaderGiftcardRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: containerised-giftcard-reader-lambda

  ReaderGiftcardLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: containerised-giftcard-reader-lambda
      Role: arn:aws:iam::334010140999:role/lambda-deployment
#      Code:
#        ImageUri: xxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/containerised-giftcard-lambda:latest
      Code:
        ImageUri: 334010140999.dkr.ecr.eu-west-1.amazonaws.com/unidays-renewal:latest # Temp image as actual imageUri is not available during this stage
      PackageType: Image
      Timeout: 900
      MemorySize: 1024